#!/system/etc/Sky/skybox sh
# PROJECT SKYNET
# Copyright CYBERDYNE (C) 2016 K1ks MoD Abhiram Shibu
###########################################################################################################################
## ______   _____          _________  ____   ______                                 _____    ______
##/      \ |     | |     |     |      |   \ /      \ |\        /|    |\        /|  |     |  |      \
##|      | |     | |     |     |      |   / |      | | \      / |    | \      / |  |     |  |       \
##|------| |-----  |-----|     |      |__/  |------| |  \    /  |    |  \    /  |  |     |  |       |
##|      | |     | |     |     |      |  \  |      | |   \  /   |    |   \  /   |  |     |  |       /
##|      | |_____| |     | ____|____  |   \ |      | |    \/    |    |    \/    |  |_____|  |______/
##
##########################################################################################################################
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

skybox=/system/etc/Sky/skybox

$skybox mount -o remount,rw / 2>/dev/null
$skybox mount -o remount,rw / / 2>/dev/null
$skybox mount -o remount,rw rootfs 2>/dev/null
$skybox mount -o remount,rw /system 2>/dev/null
$skybox mount -o remount,rw /system /system 2>/dev/null

mount -o remount,rw / 2>/dev/null
mount -o remount,rw / / 2>/dev/null
mount -o remount,rw rootfs 2>/dev/null
mount -o remount,rw /system 2>/dev/null
mount -o remount,rw /system /system 2>/dev/null

PMB=/system/etc/Sky/KGP.log

if [ -e $PMB ]; then
$skybox rm $PMB;
fi

$skybox touch $PMB;
$skybox echo "# STARTING UP OF SKYNET CONTROL CENTER : $( date +"%m-%d-%Y %H:%M:%S" )" | $skybox tee -a $PMB;
$skybox echo "" | $skybox tee -a $PMB;

# KILL GOOGLE APPS =========================================#

$skybox killall -9 com.google.android.gms
$skybox echo "=====* Kill com.google.android.gms..." | $skybox tee -a $PMB
$skybox killall -9 com.google.android.gms.persistent
$skybox echo "=====* Kill com.google.android.gms.persistent..." | $skybox tee -a $PMB
$skybox killall -9 com.google.android.gsf
$skybox echo "=====* Kill com.google.android.gsf..." | $skybox tee -a $PMB
$skybox killall -9 com.google.android.gsf.persistent
$skybox echo "=====* Kill com.google.android.gsf.persistent..." | $skybox tee -a $PMB
$skybox killall -9 com.google.process.gapps
$skybox echo "=====* Kill com.google.process.gapps..." | $skybox tee -a $PMB

$skybox echo "" | $skybox tee -a $PMB;
$skybox echo "# END OF THE SKYNET CONTROL CENTER : $( date +"%m-%d-%Y %H:%M:%S" ) " | $skybox tee -a $PMB;
