#!/system/etc/Sky/skybox sh
# PROJECT SKYNET 
# Copyright CYBERDYNE (C) 2016 K1ks
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

skybox=/system/etc/Sky/skybox

$skybox mount -o remount,rw / 2>/dev/null
$skybox mount -o remount,rw / / 2>/dev/null
$skybox mount -o remount,rw rootfs 2>/dev/null
$skybox mount -o remount,rw /system 2>/dev/null
$skybox mount -o remount,rw /system /system 2>/dev/null

mount -o remount,rw / 2>/dev/null
mount -o remount,rw / / 2>/dev/null
mount -o remount,rw rootfs 2>/dev/null
mount -o remount,rw /system 2>/dev/null
mount -o remount,rw /system /system 2>/dev/null

PMB=/system/etc/Sky/KSM.log

if [ -e $PMB ]; then
$skybox rm $PMB;
fi;

$skybox touch $PMB;
$skybox echo "# STARTING UP OF SKYNET CONTROL CENTER : $( date +"%m-%d-%Y %H:%M:%S" )" | $skybox tee -a $PMB;
$skybox echo "" | $skybox tee -a $PMB;

# KSM =========================================#

if [ -d "/sys/kernel/mm/uksm" ]; then dir=uksm
elif [ -d "/sys/kernel/mm/ksm" ]; then dir=ksm
fi;

if [ -e /sys/kernel/mm/$dir/run ]; then
$skybox echo "1" > /sys/kernel/mm/$dir/run
$skybox echo "500" > /sys/kernel/mm/$dir/sleep_millisecs
$skybox echo "50" > /sys/kernel/mm/$dir/pages_to_scan 
fi;

if [ /sys/kernel/mm/$dir/pages_to_scan=50 ]; then
$skybox echo "=====* KSM = Activated..." | $skybox tee -a $PMB; else
$skybox echo "=====* KSM = NOT Activated..." | $skybox tee -a $PMB;
fi;

$skybox echo "" | $skybox tee -a $PMB;
$skybox echo "# END OF THE SKYNET CONTROL CENTER : $( date +"%m-%d-%Y %H:%M:%S" ) " | $skybox tee -a $PMB;